name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      
      - name: Install dependencies
        run: go mod download
      
      - name: Run tests
        env:
          GOARCH: arm64
          GOOS: darwin
        run: go test -v -race ./...
